### ISSUE TITLE
Pi-top 4 ptkeyboard.keylistener not working with Vnc or Bluetooth Keyboard

### ISSUE THREAD

**Issue by Almac44** [pi-top/pi-top-Python-SDK#122]
The Further pi-top 4 Component Tutorial: Keyboard Library Example 1 stops with errors if Vnc is used for the keyboard / display or if the Pi-top FHD Display + Bluetooth Keyboard is used.
The error occurs as soon as the code is run

 27
python (runnable)
192.168.64.1 Disconnect
Run
Console Raw Output
File "/usr/lib/python3/dist-packages/Xlib/display.py"
, line 89, in __init__
self.display = _BaseDisplay(display)
File "/usr/lib/python3/dist-packages/Xlib/display.py"
, line 71, in __init__
protocol_display.Display.__init__(self, *args, **keys)
File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py"
, line 85, in __init__
name, protocol, host, displayno, screenno = connect.get_display(display)
File "/usr/lib/python3/dist-packages/Xlib/support/connect.py"
, line 73, in get_display
return mod.get_display(display)
File "/usr/lib/python3/dist-packages/Xlib/support/unix_connect.py"
, line 61, in get_display
raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""

This happens with either Vnc or FHD connections

**Comment by m-roberts** [comment]
This is for the soon-to-be-deprecated version of the library (`ptkeyboard`).

This is similar to what was addressed in #59, addressed by #61 , where the solution was to [add the DISPLAY variable](https://github.com/pi-top/pi-top-Python-SDK/pull/61/files#diff-c3b784442483c3095d0b5ba4393f9b86697d91da689c44928c1df8be514ae874R8)

This should therefore be resolved if you use `pitop.keyboard` from this SDK.
