### ISSUE TITLE
Fix OLED to automatically use the same SPI setting as the system

### ISSUE THREAD

**Issue by duwudi** [pi-top/pi-top-Python-SDK#192]
If the user has changed to use SPI 0, using the OLED with SDK doesn't work. For example, this user was using the AlexRobot class for a Further challenge and got errors:

https://forum.pi-top.com/t/pi-top-4-robotics-kit-challenges-line-follower-help-and-feedback/483/8?u=duwudi

**Comment by m-roberts** [comment]
Closing - unable to reproduce with latest version.
