### ISSUE TITLE
Raspbian OS randomly shuts down

### ISSUE THREAD

**Issue by KrazyKerbalnaut** [pi-top/pi-top-Python-SDK#207]
Raspbian OS will randomly shut down. Following firmware update at the following link does not resolve this issue. I can run the pi-top for hours and not have an issue. Other times, it will do a soft shutdown on me randomly, within 30 seconds of boot, to a couple hours after boot.

This doesn't seem to affect just Raspbian, however, it isn't as frequent in Sirius OS. I've had 2 occasions where it shut me down in Sirius, but too many to count right now on 2 hands for Raspbian.

https://knowledgebase.pi-top.com/en/knowledge/eeprom-update-for-diy-edition

**Comment by m-roberts** [comment]
Can you post this on https://forum.pi-top.com/? This is likely not an SDK issue, and we can provide better support for you there. Thanks!
