### ISSUE TITLE
Provide a exit code-based command for checking/confirming host device

### ISSUE THREAD

**Issue by m-roberts** [pi-top/pi-top-Python-SDK#398]
`systemd` supports `ExecCondition` for checking exit codes for success. Something like this would give us what we need:

```
ExecCondition=/usr/bin/pi-top devices hub --matches pi_top_4
```

**Comment by angusjfw** [comment]
this would be nice but isn't really necessary, we have used a similar approach in the [miniscreen app](https://github.com/pi-top/pi-top-4-Miniscreen/blob/781cfbd2cb24af204b2ebf5e13ed4dd7651dbe02/scripts/pt-miniscreen-should-start#L3), although reversed
